language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-puma.gemspec
- gem install sensu-plugins-puma-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: F1pgqj6ph748dkOwXGK2PKiTo0MNbaz/+XeI/5lT3OZelGsQQ4FTxTZ6LHe8O7Ge4zF+1bhxATaloXI1YVnYa1XqpawjJEcVwicU6WFdlJJkySm91xdI+3nBL7KBz4PiI0II3F/PXkmH8pjv2s2FbhDEkBwFiWTt5azqVYunZ6Y=
  gem: sensu-plugins-puma
  on:
    tags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-puma
